### ISSUE TITLE
Feature Request: Ability to remove default tooltips

### ISSUE THREAD

**Issue by Lokilotus** [Ionaru/Currency#8]
Dear Mod Authour,

Firstly apologies if this is the wrong place to post this.

I am looking to use your mod on a server I manage on behalf of the Sheffield MineCraft Society. However, we will not be using your default currency denominations as we operate an optional roleplaying component, and this uses different default currency values (most notably, a base 8 system of currency values).

I am altering the looks of the currency to be what we require by using a texture pack, and I am altering the crafting using MineTweaker, but unfortunately there is no way for me to remove the tooltips on the currency as I can tell.

We are using the 1.7.10 version of the mod. Would it be possible to get a config option or similar that removes these tooltips?

I have attached a screenshot of what I am referring to below (note I have added my own tooltip using MineTweaker to indicate the wrong tooltip to our players).
![image](https://user-images.githubusercontent.com/2342253/29432341-24ffde5c-8393-11e7-9ffa-c1666cacd6e5.png)

Many thanks,

-Alex W, President and Server Administrator of the Sheffield MineCraft Society

**Comment by Ionaru** [comment]
Thank you for your suggestion, yes this is the right place to post them. :+1: 

What you're doing with the currency sounds very interesting, cool stuff.
I can see how an option to enable/disable the tooltips would be useful, I'll work on that.
